version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            #docker pull mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
            docker images
            echo $anthos_epoc_key
            echo << pipeline.id >>
