version: 2.1
parameters:
 google-project-id:
  type: string
  default: "abc"

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    #environment:
     #projectid: << pipeline.parameters.google-project-id >>
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            #docker pull mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
            docker images
            echo $anthos_epoc_key
            echo "<< pipeline.parameters.google-project-id >>"
